### ISSUE TITLE
Guide of how to deloy this

### ISSUE THREAD

**Issue by 28development** [micheleriva/krabs#20]
Not an issue but I cant change the label to this, could you provide a guide on how to properly deploy this on platforms like digital ocean. I am not sure how to configure the subdomains and build nextjs since I have to run express.

I "simple" guide would be awesome with multiple subdomain ❤️ 

Btw cool project 👍

**Comment by micheleriva** [comment]
Hey!
Deploying a Krabs project is as easy as deploying an Express.js app.
Make sure to build your Next.js application by running `yarn next build`, and you're ready to go.

In my personal experience, it is easier to deploy any Next.js app + custom server by creating a Docker image, which can be made with ease via GitHub actions: https://github.com/marketplace/actions/build-and-push-docker-images (you can either push the image to a free and private GitHub package manager or Dockerhub).

I'll be creating a deployment guide on the official documentation at https://micheleriva.github.io/krabs. I need to work a lot on these docs, it's quite outdated, and it's my fault 😔

I'll reach back to you once the documentation is ready!

**Comment by micheleriva** [comment]
Hi @28development ,
I started to write a guide on how to deploy, but I eventually found out that there are many great articles about that on the net.
I've listed some of them in that page: https://krabs.vercel.app/docs/tutorial-basics/deployment

cheers!
