### ISSUE TITLE
rewrites dont work

### ISSUE THREAD

**Issue by AhmadAbuyahya** [micheleriva/krabs#28]
I want to add certain rewrites to one of my domains and it doesn't seem to work, this is what my next.config.js looks like:
```
module.exports = {
    async rewrites() {
        return [
            {
                source: '/someroute',
                destination: '/somepage',
            },
        ]
    },
}
```
I also tried adding the tenant name before and it also didn't work:
```
module.exports = {
    async rewrites() {
        return [
            {
                source: '/tenant/someroute',
                destination: '/tenant/somepage',
            },
        ]
    },
}
```
any help would be appreciated

**Comment by KjellConnelly** [comment]
This is how I use rewrites for catch-all route slugs... Maybe it'll give you some inspiration:

```javascript
{
   source: '/blog/:slug*',
   destination: '/website1/blog/:slug*',
},
```

**Comment by micheleriva** [comment]
Hi @AhmadAbuyahya,
you can handle rewrites on the Express.js/Fastify level

**Comment by AhmadAbuyahya** [comment]
> Hi @AhmadAbuyahya, you can handle rewrites on the Express.js/Fastify level

is there no way to handle them from next?

**Comment by micheleriva** [comment]
@AhmadAbuyahya I think Express/Fastify could do that natively, so I'd suggest using them!
