### ISSUE TITLE
How to use Krabs in Production

### ISSUE THREAD

**Issue by moayyadfaris** [micheleriva/krabs#29]
It seems that we have a problem when deploying Krabs in production mode.
Whats the guideline to go prod with Krabs?

**Comment by micheleriva** [comment]
Hey @moayyadfaris! What problem do you have specifically?
It is basically a simple Express.js/Fastify app, so make sure to follow these steps:

1. Build Next.js with `next build`
2. Make sure to expose `NODE_ENV=production`
3. Boot the Node.js server
